export const productsData = [
  {
    id: 1,
    path: "women1.jpg",
    title: "Sphynx Tie Dye Grey T-Shirt",
    quantity: 1,
    description: "Sphynx Tie Dye Grey",
    availableSizes: ["X", "L", "XL", "XXL"],
    price: 10,
    type: "women collection",
  },

  {
    id: 2,
    path: "women2.jpg",
    title: "Danger Knife Grey T-Shirt",
    quantity: 1,
    description: "Danger Knife Grey",
    availableSizes: ["X", "M", "L"],
    price: 14.9,
    type: "women collection",
  },

  {
    id: 3,
    path: "women3.jpg",
    title: "White DGK Script Tee",
    quantity: 1,
    description: "White DGK Script",
    availableSizes: ["X", "M", "L"],
    price: 14.9,
    type: "women collection",
  },

  {
    id: 4,
    path: "m1.jpg",
    title: "Born On The Streets  T-Shirt",
    quantity: 1,
    description: "Born On The Streets",
    availableSizes: ["XL"],
    price: 25.9,
    type: "men collection",
  },
  {
    id: 5,
    path: "m2.jpg",
    title: "Born On The Streets  T-Shirt",
    quantity: 1,
    description: "Born On The Streets",
    availableSizes: ["XL"],
    price: 25.9,
    type: "men collection",
  },
  {
    id: 6,
    path: "m3.jpg",
    title: "Born On The Streets  T-Shirt",
    quantity: 1,
    description: "Born On The Streets",
    availableSizes: ["XL"],
    price: 25.9,
    type: "men collection",
  },
  {
    id: 7,
    path: "ch1.jpg",
    title: "Born On The Streets  T-Shirt",
    quantity: 1,
    description: "Born On The Streets",
    availableSizes: ["XL"],
    price: 25.9,
    type: "children collection",
  },
  {
    id: 8,
    path: "ch2.jpg",
    title: "Born On The Streets  T-Shirt",
    quantity: 1,
    description: "Born On The Streets",
    availableSizes: ["XL"],
    price: 25.9,
    type: "children collection",
  },
  {
    id: 9,
    path: "ch3.jpg",
    title: "Born On The Streets  T-Shirt",
    quantity: 1,
    description: "Born On The Streets",
    availableSizes: ["XL"],
    price: 25.9,
    type: "children collection",
  },
  {
    id: 10,
    path: "ch3.jpg",
    title: "Born On The Streets  T-Shirt",
    quantity: 1,
    description: "Born On The Streets",
    availableSizes: ["XL"],
    price: 25.9,
    type: "children collection",
  },

  // {
  //   id: 5,
  //   sku: 10547961582846888,
  //   title: "Tso 3D Short Sleeve T-Shirt A",
  //   quantity: 1,
  //   description: "Tso 3D Short Sleeve",
  //   availableSizes: ["X", "L", "XL"],
  //   price: 10.9,
  //   isFreeShipping: false,
  // },

  // {
  //   id: 6,
  //   sku: 6090484789343891,
  //   title: "Man Tie Dye Cinza Grey T-Shirt",
  //   quantity: 1,
  //   description: "Man Tie Dye Cinza Grey",
  //   availableSizes: ["XL", "XXL"],
  //   price: 49.9,
  //   isFreeShipping: false,
  // },

  // {
  //   id: 7,
  //   sku: 18532669286405342,
  //   title: "Crazy Monkey Black T-Shirt",
  //   quantity: 1,
  //   description: "1977 Infantil",
  //   availableSizes: ["S"],
  //   style: "Preto com listras brancas",
  //   price: 22.5,
  //   isFreeShipping: true,
  // },

  // {
  //   id: 8,
  //   sku: 5619496040738316,
  //   title: "Tso 3D Black T-Shirt",
  //   quantity: 1,
  //   description: "",
  //   availableSizes: ["XL"],
  //   style: "Azul escuro",
  //   price: 18.7,
  //   isFreeShipping: false,
  // },
  // {
  //   id: 9,
  //   sku: 11600983276356165,
  //   title: "Crazy Monkey Grey",
  //   quantity: 1,
  //   description: "",
  //   availableSizes: ["L", "XL"],
  //   price: 134.9,
  //   isFreeShipping: true,
  // },
];
